---
- name: Join master node to Kubernetes master
  shell: >
    {{ kubernetes_join_command }} 
    --control-plane
    --certificate-key={{ lookup('file', '{{ kubernetes_secrets_dir }}{{kubernetes_cluster_name}}_cert_key.key') }}
    --apiserver-advertise-address={{hostvars[inventory_hostname].internal_network_ip}}
    creates=/etc/kubernetes/kubelet.conf
  tags: ['skip_ansible_lint']
