---
- name: Stop all KeepAlive on nodes not primary master when not setup
  shell: systemctl stop keepalived
  ignore_errors: true 
  when: kubernetes_role == 'master' 
        and (kubernetes_install_only is not defined) 
        and ( inventory_hostname != kubernetes_master_node )


- name: Initialize Kubernetes master with kubeadm init.
  command: >
    kubeadm init 
    --pod-network-cidr={{ kubernetes_pod_network_cidr }}
    --apiserver-advertise-address={{hostvars[inventory_hostname].internal_network_ip}}
    --apiserver-cert-extra-sans={{kubernetes_cluster_name}}
    --control-plane-endpoint={{ kubernetes_master_vip }}:6443
    --kubernetes-version={{ kubernetes_version_kubeadm }}
    --ignore-preflight-errors={{ kubernetes_ignore_preflight_errors }}
    --upload-certs
    --service-dns-domain={{kubernetes_cluster_name}}
    {{ kubernetes_kubeadm_init_extra_opts }}
  register: results
  become: yes

# - name: mater init
#   debug:
#     var: results

- name: write-key-file
  copy: 
    content: "{{ results.stdout | regex_search('(?:--certificate-key) (?:)(.{1,})' | string) | regex_replace('--certificate-key ','') }}"
    dest: "{{ kubernetes_secrets_dir }}{{kubernetes_cluster_name}}_cert_key.key"
  delegate_to: 127.0.0.1
  #become: yes

- name: read aconfig
  shell: cat /etc/kubernetes/admin.conf
  register: admin_conf
  become: yes
  when: inventory_hostname in groups['kubernetes-master']
  
- name: write-config-file
  copy: 
    content: "{{ admin_conf.stdout }}"
    dest: "{{ kubernetes_secrets_dir }}{{kubernetes_cluster_name}}_config"
  delegate_to: 127.0.0.1
  when: admin_conf is defined and inventory_hostname in groups['kubernetes-master']
  #become: yes

- name: install master-node-common.yml
  include_tasks: master-node-common.yml
  
- name: Configure Post Init YAML networking.
  command: "kubectl apply -f {{ item.local_address }}"
  with_items:
    - "{{ kuberbetes_yaml }}"
  register: kuberbetes_yaml_result
  changed_when: "'created' in kuberbetes_yaml_result.stdout"

- name: Check if Kubernetes Dashboard UI service already exists.
  shell: kubectl get services --namespace kube-system | grep -q kubernetes-dashboard
  changed_when: false
  failed_when: false
  register: kubernetes_dashboard_service
  when: kubernetes_enable_web_ui | bool

- name: Enable the Kubernetes Web Dashboard UI (if configured).
  command: "kubectl create -f {{ kubernetes_web_ui_manifest_file }}"
  when:
    - kubernetes_enable_web_ui | bool
    - kubernetes_dashboard_service is failed

- name: Configure Post Init Commands networking.
  command: "{{ item.command }}"
  with_items:
    - "{{ kuberbetes_commands }}"

- name: Wait for cluster ready
  shell: kubectl get nodes | awk $2 -F ' ' 'NR>1{print $2}'
  register: result
  until: result.stdout.find("Ready") != -1
  retries: 5
  delay: 20

- name: Re-Start all KeepAlive on nodes
  shell: systemctl restart keepalived
  ignore_errors: true 
  when: kubernetes_role == 'master' 
        and (kubernetes_install_only is not defined) 
        and ( inventory_hostname != kubernetes_master_node )

- name: Creates tmp (if not exist)
  file:
    path: "/tmp"
    state: directory
  when: kubernetes_role == 'master' and (kubernetes_install_only is not defined) 
        and inventory_hostname == kubernetes_master_node
#        and kubernetes_loadbalancer_vips is defined

#metallb
- name: install yml/install-metallb.yml
  include_tasks: yml/install-metallb.yml
  when: kubernetes_role == 'master' and (kubernetes_install_only is not defined) 
          and inventory_hostname == kubernetes_master_node
          and kubernetes_loadbalancer_vips is defined

## longhorn
- name: install yml/install-longhorn.yml
  include_tasks: yml/install-longhorn.yml
  when: kubernetes_install_longhorn is defined and kubernetes_install_only is not defined


